/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package torrentclient;

import com.frostwire.jlibtorrent.TorrentInfo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;


import com.frostwire.jlibtorrent.AlertListener;
import com.frostwire.jlibtorrent.LibTorrent;
import com.frostwire.jlibtorrent.SessionManager;
import com.frostwire.jlibtorrent.TorrentInfo;
import com.frostwire.jlibtorrent.alerts.AddTorrentAlert;
import com.frostwire.jlibtorrent.alerts.Alert;
import com.frostwire.jlibtorrent.alerts.AlertType;
import com.frostwire.jlibtorrent.alerts.BlockFinishedAlert;

import java.io.File;
import java.util.concurrent.CountDownLatch;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public void downloadTorrent() throws Throwable{
        String[] args = new String[]{"/home/jack/Documents/JavaProjects/TorrentClient/app/src/main/java/debian-12.5.0-amd64-netinst.iso.torrent"};

        File torrentFile = new File(args[0]);

        System.out.println("Using libtorrent version: " + LibTorrent.version());

        final SessionManager s = new SessionManager();
        final CountDownLatch signal = new CountDownLatch(1);

        s.addListener(new AlertListener() {
            @Override
            public int[] types() {
                return null;
            }

            @Override
            public void alert(Alert<?> alert) {
                AlertType type = alert.type();

                switch (type) {
                    case ADD_TORRENT:
                        System.out.println("Torrent added");
                        ((AddTorrentAlert) alert).handle().resume();
                        break;
                    case BLOCK_FINISHED:
                        BlockFinishedAlert a = (BlockFinishedAlert) alert;
                        int p = (int) (a.handle().status().progress() * 100);
                        System.out.println("Progress: " + p + " for torrent name: " + a.torrentName());
                        System.out.println(s.stats().totalDownload());
                        break;
                    case TORRENT_FINISHED:
                        System.out.println("Torrent finished");
                        signal.countDown();
                        break;
                }
            }
        });

        s.start();

        TorrentInfo ti = new TorrentInfo(torrentFile);
        s.download(ti, torrentFile.getParentFile());

        signal.await();

        s.stop();
    }



    public void getTorrentFile() throws Throwable {
        String[] args = new String[]{"/home/jack/Documents/JavaProjects/TorrentClient/app/src/main/java/debian-12.5.0-amd64-netinst.iso.torrent"};

        System.out.println("Reading with memory mapped");
        FileChannel fc = new RandomAccessFile(args[0], "r").getChannel();
        MappedByteBuffer buffer = fc.map(FileChannel.MapMode.READ_ONLY, 0, fc.size());
        TorrentInfo tInfo= new TorrentInfo(buffer);

    }

    public static void main(String[] args) throws Throwable {
        new App().downloadTorrent();
    }
}
