/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package torrentclient;

import com.frostwire.jlibtorrent.TorrentInfo;
import java.io.File;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;


public class App {

    public TorrentInfo getTorrentFile() throws Throwable {
        String[] args = new String[]{"/home/jack/Documents/JavaProjects/TorrentClient/app/src/main/java/debian-12.5.0-amd64-netinst.iso.torrent"};

        System.out.println("Reading with memory mapped");
        FileChannel fc = new RandomAccessFile(args[0], "r").getChannel();
        MappedByteBuffer buffer = fc.map(FileChannel.MapMode.READ_ONLY, 0, fc.size());
        return new TorrentInfo(buffer);

    }

    public static void main(String[] args) throws Throwable {
        new App().getTorrentFile() ;
    }
}
