/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package torrentclient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws Throwable {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getTorrentFile(), "app should have a greeting");
    }
}
